QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	--Non WL
	unemployed = { label = 'Warga', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Freelancer', payment = 1500 } } },
	bus = { label = 'Bus', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 2000 } } },
	tailor = { label = 'Penjahit', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Pekerja', payment = 2000 } } },
	miner = { label = 'Penambang', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Pekerja', payment = 2000 } } },
	slaughterer = { label = 'Peternak Ayam', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Pekerja', payment = 2000 } } },
	lumberjack = { label = 'T.Kayu', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Pekerja', payment = 2000 } } },
	reporter = { label = 'Reporter', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Journalist', payment = 2000 } } },
	trucker = { label = 'Trucker', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 2000 } } },
	garbage = { label = 'Garbage', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Collector', payment = 2000 } } },
	hotdog = { label = 'Hotdog', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Sales', payment = 2000 } } },

	police = {
		label = 'Polisi',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Tamtama', payment = 5000 },
			['1'] = { name = 'Bripda', payment = 6000 },
			['2'] = { name = 'Briptu', payment = 7000 },
			['3'] = { name = 'Brigpol', payment = 8000 },
			['4'] = { name = 'Bripka', payment = 9000 },
			['5'] = { name = 'AIPDA', payment = 10000 },
			['6'] = { name = 'AIPTU', payment = 11000 },
			['7'] = { name = 'IPDA', payment = 12000 },
			['8'] = { name = 'IPTU', payment = 13000 },
			['9'] = { name = 'AKP', payment = 14000 },
			['10'] = { name = 'Kompol', payment = 15000 },
			['11'] = { name = 'AKBP', payment = 16000 },
			['12'] = { name = 'Kombespol', payment = 17000 },
			['13'] = { name = 'Brigjend', payment = 18000 },
			['14'] = { name = 'Irjend', payment = 19000 },
			['15'] = { name = 'Komjend', isboss = true, payment = 20000 },
			['16'] = { name = 'Jendral', isboss = true, payment = 21000 },
		},
	},
	ambulance = {
		label = 'Medis',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Magang EMT', payment = 5000 },
			['1'] = { name = 'EMT STAFF', payment = 6000 },
			['2'] = { name = 'EMT SENIOR', payment = 7000 },
			['3'] = { name = 'EMT SPV', payment = 8000  },
			['4'] = { name = 'Magang Medis', payment = 9000 },
			['5'] = { name = 'Paramedic', payment = 10000  },
			['6'] = { name = 'Co.ass', payment = 11000 },
			['7'] = { name = 'Dokter Umum', isboss = true, payment = 12000 },
			['8'] = { name = 'Dokter Specialist', isboss = true, payment = 13000 },
			['9'] = { name = 'Medis SPV', isboss = true, payment = 14000 },
			['10'] = { name = 'Apoteker', isboss = true, payment = 15000 },
			['11'] = { name = 'Apoteker SPV', isboss = true, payment = 16000},
			['12'] = { name = 'HRD', isboss = true, payment = 17000},
			['13'] = { name = 'Bendahara', isboss = true, payment = 18000},
			['14'] = { name = 'Wakil Direktur', isboss = true, payment = 19000},
			['15'] = { name = 'Direktur Utama', isboss = true, payment = 20000},
			['16'] = { name = 'Komisaris RS', isboss = true, payment = 21000},
		},
	},
	realestate = {
		label = 'Real Estate',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'House Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Broker', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	taxi = {
		label = 'Taxi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Driver', payment = 75 },
			['2'] = { name = 'Event Driver', payment = 100 },
			['3'] = { name = 'Sales', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	cardealer = {
		label = 'Vehicle Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Showroom Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Finance', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	mechanic = {
		label = 'Tikum Speed',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Magang', payment = 5000 },
			['1'] = { name = 'Junior', payment = 6000 },
			['2'] = { name = 'Senior', payment = 8000 },
			['3'] = { name = 'Manager', isboss = true, payment = 9000 },
			['5'] = { name = 'Pemilik Bengkel', isboss = true, payment = 10000 },
		},
	},
	mechanic2 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	mechanic3 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	beeker = {
		label = 'Beeker\'s Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	bennys = {
		label = 'Benny\'s Original Motor Works',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
}
