QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	--Non WL
	unemployed = { label = 'Warga', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Freelancer', payment = 1500 } } },
	bus = { label = 'Bus', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 2000 } } },
	tailor = { label = 'Penjahit', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Pekerja', payment = 2000 } } },
	miner = { label = 'Penambang', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Pekerja', payment = 2000 } } },
	slaughterer = { label = 'Peternak Ayam', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Pekerja', payment = 2000 } } },
	lumberjack = { label = 'T.Kayu', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Pekerja', payment = 2000 } } },
	reporter = { label = 'Reporter', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Journalist', payment = 2000 } } },
	trucker = { label = 'Trucker', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 2000 } } },
	garbage = { label = 'Garbage', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Collector', payment = 2000 } } },
	hotdog = { label = 'Hotdog', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Sales', payment = 2000 } } },

	police = {
		label = 'Polisi',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Tamtama', payment = 300 },
			['1'] = { name = 'Bripda', payment = 370 },
			['2'] = { name = 'Briptu', payment = 390 },
			['3'] = { name = 'Brigpol', payment = 410 },
			['4'] = { name = 'Bripka', payment = 430 },
			['5'] = { name = 'AIPDA', payment = 450 },
			['6'] = { name = 'AIPTU', payment = 500 },
			['7'] = { name = 'IPDA', payment = 520 },
			['8'] = { name = 'IPTU', payment = 540 },
			['9'] = { name = 'AKP', payment = 560 },
			['10'] = { name = 'Kompol', payment = 580 },
			['11'] = { name = 'AKBP', payment = 600 },
			['12'] = { name = 'Kombespol', payment = 650 },
			['13'] = { name = 'Brigjend', payment = 660 },
			['14'] = { name = 'Irjend', payment = 670 },
			['15'] = { name = 'Komjend', isboss = true, payment = 680 },
			['16'] = { name = 'Jendral', isboss = true, payment = 700 },
		},
	},
	ambulance = {
		label = 'Medis',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'EMT', payment = 320 },
			['1'] = { name = 'Paramedic', payment = 360 },
			['2'] = { name = 'Assisten Doctor', payment = 400 },
			['3'] = { name = 'Doctor', payment = 440  },
			['4'] = { name = 'Doctor Resident', payment = 480 },
			['5'] = { name = 'Doctor Specialist', payment = 520  },
			['6'] = { name = 'Supervisor Medis', isboss = true, payment = 560 },
			['7'] = { name = 'Hrd', isboss = true, payment = 600 },
			['8'] = { name = 'Bendahara', isboss = true, payment = 670 },
			['9'] = { name = 'Wakil Direktur', isboss = true, payment = 700 },
			['10'] = { name = 'Direktur Utama', isboss = true, payment = 700 },
			['11'] = { name = 'Penasihat RS', payment = 700},
		},
	},
	realestate = {
		label = 'Real Estate',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'House Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Broker', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	taxi = {
		label = 'Taxi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Driver', payment = 75 },
			['2'] = { name = 'Event Driver', payment = 100 },
			['3'] = { name = 'Sales', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	cardealer = {
		label = 'Vehicle Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Showroom Sales', payment = 75 },
			['2'] = { name = 'Business Sales', payment = 100 },
			['3'] = { name = 'Finance', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	mechanic = {
		label = 'Tikum Speed',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Magang', payment = 200 },
			['1'] = { name = 'Junior', payment = 220 },
			['2'] = { name = 'Senior', payment = 240 },
			['3'] = { name = 'Manager', isboss = true, payment = 260 },
			['5'] = { name = 'Pemilik Bengkel', isboss = true, payment = 300 },
		},
	},
	mechanic2 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	mechanic3 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	beeker = {
		label = 'Beeker\'s Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
	bennys = {
		label = 'Benny\'s Original Motor Works',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 50 },
			['1'] = { name = 'Novice', payment = 75 },
			['2'] = { name = 'Experienced', payment = 100 },
			['3'] = { name = 'Advanced', payment = 125 },
			['4'] = { name = 'Manager', isboss = true, payment = 150 },
		},
	},
}
